### ISSUE TITLE
My game crash with quark oddities

### ISSUE THREAD

**Issue by LoloElSupremo** [ChloeDawn/BackpackBaubles#3]
When I add quark oddities and your mod my game crashes.
https://pastebin.com/ZgzTKxmK

**Comment by LoloElSupremo** [comment]
Is your mod a virus? My game still crashes while I deleted it.
https://pastebin.com/bzgzkDDt

**Comment by ChloeDawn** [comment]
I'm not sure what is causing the first crash, I will look into it. The second crash is caused because you've deleted the mod but not the *core* mod, which is in the `1.12.2` subdirectory of your mods directory. The core mod is expecting my mod to be present.

**Comment by ChloeDawn** [comment]
The first crash is being caused by two copies of my coremod being present. You need to delete `BackpackBaubles-0.1.0-core.jar` in the `1.12.2` subdirectory. I didn't account for Forge handling coremod extraction like this. I will work on avoiding this situation in the future.

**Comment by ChloeDawn** [comment]
This will be fixed in 0.2.0, but you will need to make sure to delete any and all Backpack Baubles jar files in the `mods/1.12.2` directory before launching the game. I apologize for causing this trouble.

**Comment by LoloElSupremo** [comment]
Perfect thanks if I delete the cores it works, I will try by just deleting 1
