### ISSUE TITLE
Crash after updating a different mod

### ISSUE THREAD

**Issue by Based199** [ChloeDawn/BackpackBaubles#6]
Crashed after updating LazyAE2 from 1.12.2-1.1.19 to 1.12.2-1.1.20

Using BackpackBaubles-0.2.0

crash log:
https://pastebin.com/FdWD36Ek

**Comment by ChloeDawn** [comment]
After re-reviewing #5, I've determined that these are identical issues. Your crash wasn't caused by updating the other mod, it was just coincidence. There seems to be an issue where the code can randomly fail (specifically the game code fails to load a class from my mod file).
