### ISSUE TITLE
Crash. Hope it's not a duplicate.

### ISSUE THREAD

**Issue by Kasia1403** [ChloeDawn/BackpackBaubles#9]
[crash-2022-01-09_12.50.46-client.txt](https://github.com/ChloeDawn/BackpackBaubles/files/7835172/crash-2022-01-09_12.50.46-client.txt)

**Comment by Kasia1403** [comment]
debug.log and latest log :

[debug.log](https://github.com/ChloeDawn/BackpackBaubles/files/7835184/debug.log)
[latest.log](https://github.com/ChloeDawn/BackpackBaubles/files/7835185/latest.log)

**Comment by ChloeDawn** [comment]
#7

**Comment by ChloeDawn** [comment]
If I have some free time this week I may try picking up this mod again, but as stated in the linked ticket this mod was effectively DOA (dead on arrival) as the code I interact with in Quark and Baubles are both very poorly written and it is very difficult to make them cooperate, so the mod is riddled with bugs. As for this specific crash, this is some obscure issue in Forge itself that I have no idea how to fix without rewriting the entire mod implementation from scratch.

**Comment by democat3457** [comment]
I hate to be that self-promo guy, but the RotN Edition fork of Quark provides optional, native support for adding the backpack as a bauble. Much easier than jank forge hackery lol
